<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\StructuralDashboard.Shared\StructuralDashboard.Shared.csproj" />
    <ProjectReference Include="..\StructuralDashboard.Client\StructuralDashboard.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.3" />
    <PackageReference Include="MudBlazor" Version="9.0.0" />
  </ItemGroup>
<ItemGroup>
	<StaticWebAsset Update="wwwroot/render-host.js" Fingerprint="false" />
	<StaticWebAsset Update="wwwroot/renderers/konva-renderer.js" Fingerprint="false" />
</ItemGroup>
<ItemGroup>
  <Folder Include="Data\SampleModels\" />
</ItemGroup>

</Project>
