global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using StructuralDashboard.Api;
global using StructuralDashboard.Api.Data;