// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructuralDashboard.Api.Data;

#nullable disable

namespace StructuralDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224220747_AddedNullableValues")]
    partial class AddedNullableValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Beam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FramePropertiesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsJoist")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FramePropertiesId");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Beams");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FrameProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Depth")
                        .HasColumnType("float");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("FrameProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Level", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Elevation")
                        .HasColumnType("float");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Model", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceApplication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Project", b =>
                {
                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Beam", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.FrameProperties", "FrameProperties")
                        .WithMany()
                        .HasForeignKey("FramePropertiesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("BeamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BeamId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("BeamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BeamId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamId");
                        });

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("FrameProperties");

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FrameProperties", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Level", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Model", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
