// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructuralDashboard.Api.Data;

#nullable disable

namespace StructuralDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514174826_FullModelSupport")]
    partial class FullModelSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.BeamEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FramePropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsJoist")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FramePropertiesId");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Beams");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.BraceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FramePropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLevelId");

                    b.HasIndex("FramePropertiesId");

                    b.HasIndex("ModelId");

                    b.HasIndex("TopLevelId");

                    b.ToTable("Braces");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.ColumnEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FramePropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Orientation")
                        .HasColumnType("float");

                    b.Property<string>("TopLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLevelId");

                    b.HasIndex("FramePropertiesId");

                    b.HasIndex("ModelId");

                    b.HasIndex("TopLevelId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.DiaphragmEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaphragmEntity");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FloorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaphragmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FloorPropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SpanDirection")
                        .HasColumnType("float");

                    b.Property<string>("SurfaceLoadId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiaphragmId");

                    b.HasIndex("FloorPropertiesId");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SurfaceLoadId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FloorPropertiesEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModelingType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlabType")
                        .HasColumnType("int");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("FloorProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FramePropertiesEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("FrameProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.GridEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.IsolatedFootingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Orientation")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Footings");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.LevelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Elevation")
                        .HasColumnType("float");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.MaterialEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("CoefficientOfThermalExpansion")
                        .HasColumnType("float");

                    b.Property<int?>("DirectionalSymmetryType")
                        .HasColumnType("int");

                    b.Property<double?>("ElasticModulus")
                        .HasColumnType("float");

                    b.Property<double?>("MassPerUnitVolume")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PoissonsRatio")
                        .HasColumnType("float");

                    b.Property<double?>("ShearModulus")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPerUnitVolume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.OpeningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Openings");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.ProjectEntity", b =>
                {
                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.StructuralModelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceApplication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.SurfaceLoadEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurfaceLoadEntity");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.WallEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLevelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PropertiesId");

                    b.HasIndex("TopLevelId");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.WallPropertiesEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Thickness")
                        .HasColumnType("float");

                    b.Property<double?>("UnitWeightForSelfWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("WallProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.BeamEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.FramePropertiesEntity", "FrameProperties")
                        .WithMany()
                        .HasForeignKey("FramePropertiesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("BeamEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BeamEntityId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.FrameModifiersEntity", "FrameModifiers", b1 =>
                        {
                            b1.Property<string>("BeamEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("A22")
                                .HasColumnType("float");

                            b1.Property<double?>("A33")
                                .HasColumnType("float");

                            b1.Property<double?>("Area")
                                .HasColumnType("float");

                            b1.Property<double?>("I22")
                                .HasColumnType("float");

                            b1.Property<double?>("I33")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("Torsion")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("BeamEntityId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("BeamEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BeamEntityId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamEntityId");
                        });

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("FrameModifiers");

                    b.Navigation("FrameProperties");

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.BraceEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "BaseLevel")
                        .WithMany()
                        .HasForeignKey("BaseLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.FramePropertiesEntity", "FrameProperties")
                        .WithMany()
                        .HasForeignKey("FramePropertiesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "TopLevel")
                        .WithMany()
                        .HasForeignKey("TopLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("BraceEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BraceEntityId");

                            b1.ToTable("Braces");

                            b1.WithOwner()
                                .HasForeignKey("BraceEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.FrameModifiersEntity", "FrameModifiers", b1 =>
                        {
                            b1.Property<string>("BraceEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("A22")
                                .HasColumnType("float");

                            b1.Property<double?>("A33")
                                .HasColumnType("float");

                            b1.Property<double?>("Area")
                                .HasColumnType("float");

                            b1.Property<double?>("I22")
                                .HasColumnType("float");

                            b1.Property<double?>("I33")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("Torsion")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("BraceEntityId");

                            b1.ToTable("Braces");

                            b1.WithOwner()
                                .HasForeignKey("BraceEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("BraceEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BraceEntityId");

                            b1.ToTable("Braces");

                            b1.WithOwner()
                                .HasForeignKey("BraceEntityId");
                        });

                    b.Navigation("BaseLevel");

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("FrameModifiers");

                    b.Navigation("FrameProperties");

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();

                    b.Navigation("TopLevel");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.ColumnEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "BaseLevel")
                        .WithMany()
                        .HasForeignKey("BaseLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.FramePropertiesEntity", "FrameProperties")
                        .WithMany()
                        .HasForeignKey("FramePropertiesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "TopLevel")
                        .WithMany()
                        .HasForeignKey("TopLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("ColumnEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("ColumnEntityId");

                            b1.ToTable("Columns");

                            b1.WithOwner()
                                .HasForeignKey("ColumnEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.FrameModifiersEntity", "FrameModifiers", b1 =>
                        {
                            b1.Property<string>("ColumnEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("A22")
                                .HasColumnType("float");

                            b1.Property<double?>("A33")
                                .HasColumnType("float");

                            b1.Property<double?>("Area")
                                .HasColumnType("float");

                            b1.Property<double?>("I22")
                                .HasColumnType("float");

                            b1.Property<double?>("I33")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("Torsion")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("ColumnEntityId");

                            b1.ToTable("Columns");

                            b1.WithOwner()
                                .HasForeignKey("ColumnEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("ColumnEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("ColumnEntityId");

                            b1.ToTable("Columns");

                            b1.WithOwner()
                                .HasForeignKey("ColumnEntityId");
                        });

                    b.Navigation("BaseLevel");

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("FrameModifiers");

                    b.Navigation("FrameProperties");

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();

                    b.Navigation("TopLevel");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FloorEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.DiaphragmEntity", "Diaphragm")
                        .WithMany()
                        .HasForeignKey("DiaphragmId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.FloorPropertiesEntity", "FloorProperties")
                        .WithMany()
                        .HasForeignKey("FloorPropertiesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.SurfaceLoadEntity", "SurfaceLoad")
                        .WithMany()
                        .HasForeignKey("SurfaceLoadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsMany("StructuralDashboard.Shared.Shared.Point", "Points", b1 =>
                        {
                            b1.Property<string>("FloorEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.Property<double>("Z");

                            b1.HasKey("FloorEntityId", "__synthesizedOrdinal");

                            b1.ToTable("Floors");

                            b1
                                .ToJson("Points")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("FloorEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShellModifiersEntity", "ShellModifiers", b1 =>
                        {
                            b1.Property<string>("FloorEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("F11")
                                .HasColumnType("float");

                            b1.Property<double?>("F12")
                                .HasColumnType("float");

                            b1.Property<double?>("F22")
                                .HasColumnType("float");

                            b1.Property<double?>("M11")
                                .HasColumnType("float");

                            b1.Property<double?>("M12")
                                .HasColumnType("float");

                            b1.Property<double?>("M22")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("V13")
                                .HasColumnType("float");

                            b1.Property<double?>("V23")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("FloorEntityId");

                            b1.ToTable("Floors");

                            b1.WithOwner()
                                .HasForeignKey("FloorEntityId");
                        });

                    b.Navigation("Diaphragm");

                    b.Navigation("FloorProperties");

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("Points");

                    b.Navigation("ShellModifiers");

                    b.Navigation("SurfaceLoad");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FloorPropertiesEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Entities.DeckPropertiesEntity", "DeckProperties", b1 =>
                        {
                            b1.Property<string>("FloorPropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("DeckShearThickness")
                                .HasColumnType("float");

                            b1.Property<string>("DeckType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("DeckUnitWeight")
                                .HasColumnType("float");

                            b1.Property<string>("MaterialId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("RibDepth")
                                .HasColumnType("float");

                            b1.Property<double>("RibSpacing")
                                .HasColumnType("float");

                            b1.Property<double>("RibWidthBottom")
                                .HasColumnType("float");

                            b1.Property<double>("RibWidthTop")
                                .HasColumnType("float");

                            b1.HasKey("FloorPropertiesEntityId");

                            b1.ToTable("FloorProperties");

                            b1.WithOwner()
                                .HasForeignKey("FloorPropertiesEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShellModifiersEntity", "ShellModifiers", b1 =>
                        {
                            b1.Property<string>("FloorPropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("F11")
                                .HasColumnType("float");

                            b1.Property<double?>("F12")
                                .HasColumnType("float");

                            b1.Property<double?>("F22")
                                .HasColumnType("float");

                            b1.Property<double?>("M11")
                                .HasColumnType("float");

                            b1.Property<double?>("M12")
                                .HasColumnType("float");

                            b1.Property<double?>("M22")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("V13")
                                .HasColumnType("float");

                            b1.Property<double?>("V23")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("FloorPropertiesEntityId");

                            b1.ToTable("FloorProperties");

                            b1.WithOwner()
                                .HasForeignKey("FloorPropertiesEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShearStudPropertiesEntity", "ShearStudProperties", b1 =>
                        {
                            b1.Property<string>("FloorPropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("ShearStudDiameter")
                                .HasColumnType("float");

                            b1.Property<double?>("ShearStudHeight")
                                .HasColumnType("float");

                            b1.Property<double?>("ShearStudTensileStrength")
                                .HasColumnType("float");

                            b1.HasKey("FloorPropertiesEntityId");

                            b1.ToTable("FloorProperties");

                            b1.WithOwner()
                                .HasForeignKey("FloorPropertiesEntityId");
                        });

                    b.Navigation("DeckProperties");

                    b.Navigation("Material");

                    b.Navigation("Model");

                    b.Navigation("ShearStudProperties");

                    b.Navigation("ShellModifiers");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FramePropertiesEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ConcreteFramePropertiesEntity", "ConcreteProps", b1 =>
                        {
                            b1.Property<string>("FramePropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Depth")
                                .HasColumnType("float");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SectionType")
                                .HasColumnType("int");

                            b1.Property<double>("Width")
                                .HasColumnType("float");

                            b1.HasKey("FramePropertiesEntityId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.FrameModifiersEntity", "FrameModifiers", b1 =>
                        {
                            b1.Property<string>("FramePropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("A22")
                                .HasColumnType("float");

                            b1.Property<double?>("A33")
                                .HasColumnType("float");

                            b1.Property<double?>("Area")
                                .HasColumnType("float");

                            b1.Property<double?>("I22")
                                .HasColumnType("float");

                            b1.Property<double?>("I33")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("Torsion")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("FramePropertiesEntityId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.SteelFramePropertiesEntity", "SteelProps", b1 =>
                        {
                            b1.Property<string>("FramePropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SectionType")
                                .HasColumnType("int");

                            b1.HasKey("FramePropertiesEntityId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.WoodFramePropertiesEntity", "WoodProps", b1 =>
                        {
                            b1.Property<string>("FramePropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Depth")
                                .HasColumnType("float");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SectionType")
                                .HasColumnType("int");

                            b1.Property<double>("Width")
                                .HasColumnType("float");

                            b1.HasKey("FramePropertiesEntityId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesEntityId");
                        });

                    b.Navigation("ConcreteProps");

                    b.Navigation("FrameModifiers");

                    b.Navigation("Material");

                    b.Navigation("Model");

                    b.Navigation("SteelProps");

                    b.Navigation("WoodProps");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.GridEntity", b =>
                {
                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("GridEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("GridEntityId");

                            b1.ToTable("Grids");

                            b1.WithOwner()
                                .HasForeignKey("GridEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("GridEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("GridEntityId");

                            b1.ToTable("Grids");

                            b1.WithOwner()
                                .HasForeignKey("GridEntityId");
                        });

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("StartPoint")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.IsolatedFootingEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "Point", b1 =>
                        {
                            b1.Property<string>("IsolatedFootingEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("IsolatedFootingEntityId");

                            b1.ToTable("Footings");

                            b1.WithOwner()
                                .HasForeignKey("IsolatedFootingEntityId");
                        });

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("Point")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.LevelEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.MaterialEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ConcreteMaterialPropertiesEntity", "ConcreteProps", b1 =>
                        {
                            b1.Property<string>("MaterialEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("Fc")
                                .HasColumnType("float");

                            b1.Property<double?>("ShearStrengthReductionFactor")
                                .HasColumnType("float");

                            b1.Property<int?>("WeightClass")
                                .HasColumnType("int");

                            b1.HasKey("MaterialEntityId");

                            b1.ToTable("Materials");

                            b1.WithOwner()
                                .HasForeignKey("MaterialEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.SteelMaterialPropertiesEntity", "SteelProps", b1 =>
                        {
                            b1.Property<string>("MaterialEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("Fu")
                                .HasColumnType("float");

                            b1.Property<double?>("Fue")
                                .HasColumnType("float");

                            b1.Property<double?>("Fy")
                                .HasColumnType("float");

                            b1.Property<double?>("Fye")
                                .HasColumnType("float");

                            b1.HasKey("MaterialEntityId");

                            b1.ToTable("Materials");

                            b1.WithOwner()
                                .HasForeignKey("MaterialEntityId");
                        });

                    b.Navigation("ConcreteProps");

                    b.Navigation("Model");

                    b.Navigation("SteelProps");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.OpeningEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("StructuralDashboard.Shared.Shared.Point", "Points", b1 =>
                        {
                            b1.Property<string>("OpeningEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.Property<double>("Z");

                            b1.HasKey("OpeningEntityId", "__synthesizedOrdinal");

                            b1.ToTable("Openings");

                            b1
                                .ToJson("Points")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("OpeningEntityId");
                        });

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.StructuralModelEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.WallEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "BaseLevel")
                        .WithMany()
                        .HasForeignKey("BaseLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.WallPropertiesEntity", "Properties")
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.LevelEntity", "TopLevel")
                        .WithMany()
                        .HasForeignKey("TopLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("WallEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("WallEntityId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallEntityId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("WallEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("WallEntityId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallEntityId");
                        });

                    b.Navigation("BaseLevel");

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Properties");

                    b.Navigation("StartPoint")
                        .IsRequired();

                    b.Navigation("TopLevel");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.WallPropertiesEntity", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.StructuralModelEntity", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShellModifiersEntity", "ETABSModifiers", b1 =>
                        {
                            b1.Property<string>("WallPropertiesEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double?>("F11")
                                .HasColumnType("float");

                            b1.Property<double?>("F12")
                                .HasColumnType("float");

                            b1.Property<double?>("F22")
                                .HasColumnType("float");

                            b1.Property<double?>("M11")
                                .HasColumnType("float");

                            b1.Property<double?>("M12")
                                .HasColumnType("float");

                            b1.Property<double?>("M22")
                                .HasColumnType("float");

                            b1.Property<double?>("Mass")
                                .HasColumnType("float");

                            b1.Property<double?>("V13")
                                .HasColumnType("float");

                            b1.Property<double?>("V23")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("WallPropertiesEntityId");

                            b1.ToTable("WallProperties");

                            b1.WithOwner()
                                .HasForeignKey("WallPropertiesEntityId");
                        });

                    b.Navigation("ETABSModifiers");

                    b.Navigation("Material");

                    b.Navigation("Model");
                });
#pragma warning restore 612, 618
        }
    }
}
