// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructuralDashboard.Api.Data;

#nullable disable

namespace StructuralDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314231317_ModelElements")]
    partial class ModelElements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Beam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FramePropertiesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsJoist")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Beams");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Brace", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLevelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("TopLevelId");

                    b.ToTable("Braces");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Column", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Orientation")
                        .HasColumnType("float");

                    b.Property<string>("TopLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLevelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("TopLevelId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.DeckProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DeckShearThickness")
                        .HasColumnType("float");

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DeckUnitWeight")
                        .HasColumnType("float");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("RibDepth")
                        .HasColumnType("float");

                    b.Property<double>("RibSpacing")
                        .HasColumnType("float");

                    b.Property<double>("RibWidthBottom")
                        .HasColumnType("float");

                    b.Property<double>("RibWidthTop")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("DeckProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Diaphragm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Diaphragm");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaphragmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FloorPropertiesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SpanDirection")
                        .HasColumnType("float");

                    b.Property<string>("SurfaceLoadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiaphragmId");

                    b.HasIndex("FloorPropertiesId");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SurfaceLoadId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FloorProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeckPropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModelingType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlabType")
                        .HasColumnType("int");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckPropertiesId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("FloorProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FrameModifiers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("A22")
                        .HasColumnType("float");

                    b.Property<double>("A33")
                        .HasColumnType("float");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<double>("I22")
                        .HasColumnType("float");

                    b.Property<double>("I33")
                        .HasColumnType("float");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<double>("Torsion")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FrameModifiers");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FrameProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FrameModifersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FrameModifersId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("FrameProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Grid", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.IsolatedFooting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Orientation")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Footings");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Level", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Elevation")
                        .HasColumnType("float");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("CoefficientOfThermalExpansion")
                        .HasColumnType("float");

                    b.Property<int?>("DirectionalSymmetryType")
                        .HasColumnType("int");

                    b.Property<double?>("ElasticModulus")
                        .HasColumnType("float");

                    b.Property<double?>("MassPerUnitVolume")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PoissonsRatio")
                        .HasColumnType("float");

                    b.Property<double?>("ShearModulus")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPerUnitVolume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Model", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceApplication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Opening", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Openings");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Project", b =>
                {
                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.SurfaceLoad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurfaceLoad");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Wall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLateral")
                        .HasColumnType("bit");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertiesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseLevelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PropertiesId");

                    b.HasIndex("TopLevelId");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.WallProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("WallProperties");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Beam", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("BeamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BeamId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("BeamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BeamId");

                            b1.ToTable("Beams");

                            b1.WithOwner()
                                .HasForeignKey("BeamId");
                        });

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Brace", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "BaseLevel")
                        .WithMany()
                        .HasForeignKey("BaseLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "TopLevel")
                        .WithMany()
                        .HasForeignKey("TopLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("BraceId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BraceId");

                            b1.ToTable("Braces");

                            b1.WithOwner()
                                .HasForeignKey("BraceId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("BraceId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("BraceId");

                            b1.ToTable("Braces");

                            b1.WithOwner()
                                .HasForeignKey("BraceId");
                        });

                    b.Navigation("BaseLevel");

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();

                    b.Navigation("TopLevel");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Column", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "BaseLevel")
                        .WithMany()
                        .HasForeignKey("BaseLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "TopLevel")
                        .WithMany()
                        .HasForeignKey("TopLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("ColumnId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("ColumnId");

                            b1.ToTable("Columns");

                            b1.WithOwner()
                                .HasForeignKey("ColumnId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("ColumnId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("ColumnId");

                            b1.ToTable("Columns");

                            b1.WithOwner()
                                .HasForeignKey("ColumnId");
                        });

                    b.Navigation("BaseLevel");

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("StartPoint")
                        .IsRequired();

                    b.Navigation("TopLevel");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.DeckProperties", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Floor", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Diaphragm", "Diaphragm")
                        .WithMany()
                        .HasForeignKey("DiaphragmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.FloorProperties", "FloorProperties")
                        .WithMany()
                        .HasForeignKey("FloorPropertiesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.SurfaceLoad", "SurfaceLoad")
                        .WithMany()
                        .HasForeignKey("SurfaceLoadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("StructuralDashboard.Shared.Shared.Point", "Points", b1 =>
                        {
                            b1.Property<string>("FloorId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.Property<double>("Z");

                            b1.HasKey("FloorId", "__synthesizedOrdinal");

                            b1.ToTable("Floors");

                            b1
                                .ToJson("Points")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("FloorId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShellModifiers", "ShellModifiers", b1 =>
                        {
                            b1.Property<string>("FloorId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("F11")
                                .HasColumnType("float");

                            b1.Property<double>("F12")
                                .HasColumnType("float");

                            b1.Property<double>("F22")
                                .HasColumnType("float");

                            b1.Property<double>("M11")
                                .HasColumnType("float");

                            b1.Property<double>("M12")
                                .HasColumnType("float");

                            b1.Property<double>("M22")
                                .HasColumnType("float");

                            b1.Property<double>("Mass")
                                .HasColumnType("float");

                            b1.Property<double>("V13")
                                .HasColumnType("float");

                            b1.Property<double>("V23")
                                .HasColumnType("float");

                            b1.Property<double>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("FloorId");

                            b1.ToTable("Floors");

                            b1.WithOwner()
                                .HasForeignKey("FloorId");
                        });

                    b.Navigation("Diaphragm");

                    b.Navigation("FloorProperties");

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("Points");

                    b.Navigation("ShellModifiers")
                        .IsRequired();

                    b.Navigation("SurfaceLoad");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FloorProperties", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.DeckProperties", "DeckProperties")
                        .WithMany()
                        .HasForeignKey("DeckPropertiesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShellModifiers", "ShellModifiers", b1 =>
                        {
                            b1.Property<string>("FloorPropertiesId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("F11")
                                .HasColumnType("float");

                            b1.Property<double>("F12")
                                .HasColumnType("float");

                            b1.Property<double>("F22")
                                .HasColumnType("float");

                            b1.Property<double>("M11")
                                .HasColumnType("float");

                            b1.Property<double>("M12")
                                .HasColumnType("float");

                            b1.Property<double>("M22")
                                .HasColumnType("float");

                            b1.Property<double>("Mass")
                                .HasColumnType("float");

                            b1.Property<double>("V13")
                                .HasColumnType("float");

                            b1.Property<double>("V23")
                                .HasColumnType("float");

                            b1.Property<double>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("FloorPropertiesId");

                            b1.ToTable("FloorProperties");

                            b1.WithOwner()
                                .HasForeignKey("FloorPropertiesId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ShearStudProperties", "ShearStudProperties", b1 =>
                        {
                            b1.Property<string>("FloorPropertiesId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("ShearStudDiameter")
                                .HasColumnType("float");

                            b1.Property<double>("ShearStudHeight")
                                .HasColumnType("float");

                            b1.Property<double>("ShearStudTensileStrength")
                                .HasColumnType("float");

                            b1.HasKey("FloorPropertiesId");

                            b1.ToTable("FloorProperties");

                            b1.WithOwner()
                                .HasForeignKey("FloorPropertiesId");
                        });

                    b.Navigation("DeckProperties");

                    b.Navigation("Material");

                    b.Navigation("Model");

                    b.Navigation("ShearStudProperties")
                        .IsRequired();

                    b.Navigation("ShellModifiers")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.FrameProperties", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.FrameModifiers", "FrameModifers")
                        .WithMany()
                        .HasForeignKey("FrameModifersId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StructuralDashboard.Shared.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Entities.ConcreteFrameProperties", "ConcreteProps", b1 =>
                        {
                            b1.Property<string>("FramePropertiesId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Depth")
                                .HasColumnType("float");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SectionType")
                                .HasColumnType("int");

                            b1.Property<double>("Width")
                                .HasColumnType("float");

                            b1.HasKey("FramePropertiesId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.SteelFrameProperties", "SteelProps", b1 =>
                        {
                            b1.Property<string>("FramePropertiesId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SectionType")
                                .HasColumnType("int");

                            b1.HasKey("FramePropertiesId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Entities.WoodFrameProperties", "WoodProps", b1 =>
                        {
                            b1.Property<string>("FramePropertiesId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Depth")
                                .HasColumnType("float");

                            b1.Property<string>("SectionName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SectionType")
                                .HasColumnType("int");

                            b1.Property<double>("Width")
                                .HasColumnType("float");

                            b1.HasKey("FramePropertiesId");

                            b1.ToTable("FrameProperties");

                            b1.WithOwner()
                                .HasForeignKey("FramePropertiesId");
                        });

                    b.Navigation("ConcreteProps")
                        .IsRequired();

                    b.Navigation("FrameModifers");

                    b.Navigation("Material");

                    b.Navigation("Model");

                    b.Navigation("SteelProps")
                        .IsRequired();

                    b.Navigation("WoodProps")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Grid", b =>
                {
                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("GridId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("GridId");

                            b1.ToTable("Grids");

                            b1.WithOwner()
                                .HasForeignKey("GridId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("GridId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("GridId");

                            b1.ToTable("Grids");

                            b1.WithOwner()
                                .HasForeignKey("GridId");
                        });

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("StartPoint")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.IsolatedFooting", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "Point", b1 =>
                        {
                            b1.Property<string>("IsolatedFootingId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("IsolatedFootingId");

                            b1.ToTable("Footings");

                            b1.WithOwner()
                                .HasForeignKey("IsolatedFootingId");
                        });

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("Point")
                        .IsRequired();
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Level", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Material", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Model", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Opening", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("StructuralDashboard.Shared.Shared.Point", "Points", b1 =>
                        {
                            b1.Property<string>("OpeningId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.Property<double>("Z");

                            b1.HasKey("OpeningId", "__synthesizedOrdinal");

                            b1.ToTable("Openings");

                            b1
                                .ToJson("Points")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("OpeningId");
                        });

                    b.Navigation("Level");

                    b.Navigation("Model");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.Wall", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "BaseLevel")
                        .WithMany()
                        .HasForeignKey("BaseLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.WallProperties", "Properties")
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Level", "TopLevel")
                        .WithMany()
                        .HasForeignKey("TopLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "EndPoint", b1 =>
                        {
                            b1.Property<string>("WallId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.OwnsOne("StructuralDashboard.Shared.Shared.Point", "StartPoint", b1 =>
                        {
                            b1.Property<string>("WallId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("WallId");

                            b1.ToTable("Walls");

                            b1.WithOwner()
                                .HasForeignKey("WallId");
                        });

                    b.Navigation("BaseLevel");

                    b.Navigation("EndPoint")
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Properties");

                    b.Navigation("StartPoint")
                        .IsRequired();

                    b.Navigation("TopLevel");
                });

            modelBuilder.Entity("StructuralDashboard.Shared.Entities.WallProperties", b =>
                {
                    b.HasOne("StructuralDashboard.Shared.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StructuralDashboard.Shared.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Model");
                });
#pragma warning restore 612, 618
        }
    }
}
